---
- name: Playbook para borrar la infraestructura de la práctica 09
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Inclusión del archivo de variables
      ansible.builtin.include_vars: vars/variables.yaml

    - name: Obtención del ID de la instancia balancer mediante el nombre
      amazon.aws.ec2_instance_info:
        filters:
          "tag:Name": "{{ Instance_balancer.ec2_instance_name }}"
          "instance-state-name": "running"

      register: ec2_instance_balancer_name

    - name: Desasociación de la IP elástica de la instancia balancer y liberación de la misma
      community.aws.ec2_eip:
        device_id: "{{ ec2_instance_balancer_name.instances[0].instance_id }}"
        release_on_disassociation: true
        state: absent

    - name: Eliminación de las instancias mediante loop
      amazon.aws.ec2_instance:
        filters:
          "tag:Name": "{{ item }}"
        state: absent
      loop:
        - "{{ Instance_balancer.ec2_instance_name }}"
        - "{{ Instance_frontend_01.ec2_instance_name }}"
        - "{{ Instance_frontend_02.ec2_instance_name }}"
        - "{{ Instance_backend.ec2_instance_name }}"
        - "{{ Instance_nfs.ec2_instance_name }}"

    - name: Eliminación de los grupos de seguridad mediante loop
      amazon.aws.ec2_security_group:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ SG_Balancer.ec2_security_group_name }}"
        - "{{ SG_Frontend.ec2_security_group_name }}"
        - "{{ SG_Backend.ec2_security_group_name }}"
        - "{{ SG_Nfs.ec2_security_group_name }}"
